apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: openshift-kube-scheduler
  name: system:openshift:operator:kube-scheduler:public
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: system:openshift:operator:kube-scheduler:public
subjects:
- kind: Group
  name: system:authenticated
